# Generated by Django 4.2.25 on 2025-11-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('course_code', models.CharField(db_index=True, max_length=16)),
                ('topic', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=10)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer')], max_length=20)),
                ('question_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_generated_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('student_id', models.CharField(db_index=True, max_length=64)),
                ('answer_text', models.TextField()),
                ('grading_result', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai_question_generator.generatedquestion')),
            ],
            options={
                'db_table': 'ai_student_answer',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(db_index=True, max_length=16)),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=10, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('sample_answer', models.TextField(blank=True, null=True)),
                ('grading_points', models.JSONField(blank=True, null=True)),
                ('score', models.IntegerField(default=10)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ai_sample_question',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course_code', 'topic'], name='ai_sample_q_course__fb54ed_idx'), models.Index(fields=['topic', 'difficulty'], name='ai_sample_q_topic_c9970c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['session_id'], name='ai_generate_session_df2ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['course_code', 'topic'], name='ai_generate_course__7f29d9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['session_id', 'student_id'], name='ai_student__session_a55c40_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['student_id', 'submitted_at'], name='ai_student__student_25ceaf_idx'),
        ),
    ]
