# Generated by Django 4.2.25 on 2025-11-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
