# Generated by Django 4.2.25 on 2025-11-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_chatconversation_last_activity_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSetupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('step', models.CharField(choices=[('course', 'Course Selection'), ('topic', 'Topic Selection'), ('generating', 'Generating Practice')], max_length=20)),
                ('course', models.CharField(blank=True, max_length=10, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
