# Generated by Django 4.2.25 on 2025-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0003_practicesetupstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlanQnAState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('current_mode', models.CharField(choices=[('general_chat', 'General Chat'), ('practice_setup', 'Practice Setup'), ('study_plan_qna', 'Study Plan Q&A')], default='general_chat', max_length=20)),
                ('sub_state', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
