# Generated by Django 4.2.25 on 2025-11-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0004_studyplanqnastate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentPracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=20)),
                ('session_id', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=16)),
                ('topic', models.CharField(max_length=255)),
                ('total_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('questions_count', models.IntegerField(default=0)),
                ('test_data', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recent_practice_session',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student_id', '-completed_at'], name='recent_prac_student_80ca9b_idx')],
            },
        ),
    ]
