# Generated by Django 4.2.25 on 2025-11-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0005_recentpracticesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesetupstate',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practicesetupstate',
            name='num_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicesetupstate',
            name='step',
            field=models.CharField(choices=[('course', 'Course Selection'), ('topic', 'Topic Selection'), ('num_questions', 'Number of Questions'), ('difficulty', 'Difficulty Selection'), ('generating', 'Generating Practice')], max_length=20),
        ),
    ]
