# Generated by Django 5.2.7 on 2025-11-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(db_index=True, max_length=64)),
                ("week_start_date", models.DateField()),
                ("week_offset", models.IntegerField(default=0)),
                ("tz", models.CharField(default="Australia/Sydney", max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[("ai", "AI"), ("manual", "Manual")],
                        default="ai",
                        max_length=10,
                    ),
                ),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "study_plan",
                "indexes": [
                    models.Index(
                        fields=["student_id", "week_start_date"],
                        name="study_plan_student_ace1aa_idx",
                    ),
                    models.Index(
                        fields=["student_id", "week_offset"],
                        name="study_plan_student_6c30f7_idx",
                    ),
                ],
                "unique_together": {("student_id", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="StudyPlanItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_item_id", models.CharField(max_length=128)),
                ("course_code", models.CharField(db_index=True, max_length=32)),
                (
                    "course_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("minutes", models.IntegerField()),
                ("part_index", models.IntegerField()),
                ("parts_count", models.IntegerField()),
                ("part_title", models.CharField(blank=True, max_length=255, null=True)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="plans.studyplan",
                    ),
                ),
            ],
            options={
                "db_table": "study_plan_item",
                "indexes": [
                    models.Index(
                        fields=["plan", "scheduled_date"],
                        name="study_plan__plan_id_31d0ba_idx",
                    ),
                    models.Index(
                        fields=["course_code", "scheduled_date"],
                        name="study_plan__course__6c1d43_idx",
                    ),
                ],
                "unique_together": {("plan", "external_item_id")},
            },
        ),
    ]
