# Generated by Django 5.2.7 on 2025-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(db_index=True, max_length=50)),
                ("course_code", models.CharField(blank=True, max_length=20, null=True)),
                ("task_id", models.IntegerField(blank=True, null=True)),
                ("message_type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("preview", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("due_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student_id", "message_type", "created_at"],
                        name="reminder_no_student_a275b8_idx",
                    )
                ],
            },
        ),
    ]
