# Generated by Django 5.2.7 on 2025-11-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("student_id", "task_id", "message_type"), name="uniq_notify"
            ),
        ),
    ]
