# Generated by Django 5.2.7 on 2025-11-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_coursetask_deadline"),
        ("reminder", "0002_notification_uniq_notify"),
    ]

    operations = [
        migrations.CreateModel(
            name="DueReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="student ID"
                    ),
                ),
                (
                    "total_due_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total due days"
                    ),
                ),
                (
                    "consecutive_due_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="consecutive due days"
                    ),
                ),
                (
                    "last_overdue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last due date"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="due_reports",
                        to="courses.coursetask",
                        verbose_name="course task",
                    ),
                ),
            ],
            options={
                "db_table": "reminder_duereport",
                "unique_together": {("student_id", "task")},
            },
        ),
    ]
