# Generated by Django 4.2.25 on 2025-11-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=64)),
                ('task_id', models.PositiveIntegerField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_progress',
                'indexes': [models.Index(fields=['student_id'], name='task_progre_student_6ab5c1_idx'), models.Index(fields=['task_id'], name='task_progre_task_id_22502d_idx')],
                'unique_together': {('student_id', 'task_id')},
            },
        ),
    ]
