# Generated by Django 5.2.7 on 2025-11-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_progress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverdueCourseStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(max_length=64)),
                ("course_code", models.CharField(max_length=32)),
                ("task_id", models.CharField(max_length=64)),
                ("count_overdue", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "overdue_course_student",
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="overdue_cou_student_ee2dae_idx"
                    ),
                    models.Index(
                        fields=["course_code"], name="overdue_cou_course__5534cb_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="overdue_cou_task_id_ae0116_idx"
                    ),
                ],
                "unique_together": {("student_id", "course_code", "task_id")},
            },
        ),
        migrations.CreateModel(
            name="OverdueStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(max_length=64, unique=True)),
                ("count_overdue", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "overdue_student",
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="overdue_stu_student_548992_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OverdueStudentDailyLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "overdue_student_daily_log",
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="overdue_stu_student_254073_idx"
                    ),
                    models.Index(fields=["date"], name="overdue_stu_date_838780_idx"),
                ],
                "unique_together": {("student_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="OverdueTaskDailyLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(max_length=64)),
                ("course_code", models.CharField(max_length=32)),
                ("task_id", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "overdue_task_daily_log",
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="overdue_tas_student_520fda_idx"
                    ),
                    models.Index(
                        fields=["course_code", "task_id"],
                        name="overdue_tas_course__9013f2_idx",
                    ),
                    models.Index(fields=["date"], name="overdue_tas_date_fe00b3_idx"),
                ],
                "unique_together": {("student_id", "course_code", "task_id", "date")},
            },
        ),
    ]
