# Generated by Django 5.2.7 on 2025-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentaccount",
            name="student_id",
        ),
        migrations.AddField(
            model_name="studentaccount",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="studentaccount",
            name="email",
            field=models.EmailField(
                max_length=254, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
