# Generated by Django 5.2.7 on 2025-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAccount",
            fields=[
                (
                    "admin_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=254, unique=True)),
                ("full_name", models.CharField(default="Unknown", max_length=100)),
                ("password_hash", models.CharField(max_length=128)),
                ("avatar_url", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "current_token",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("token_issued_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounts_adminaccount",
                "indexes": [
                    models.Index(
                        fields=["current_token"], name="accounts_ad_current_75ddf9_idx"
                    )
                ],
            },
        ),
    ]
