# Generated by Django 5.2.7 on 2025-10-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentAccount",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=60)),
            ],
        ),
    ]
