# Generated by Django 5.2.7 on 2025-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentaccount",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
