# Generated by Django 5.2.7 on 2025-10-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_studentaccount_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentaccount",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
