# Generated by Django 5.2.7 on 2025-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_studentaccount_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentaccount",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
