# Generated by Django 5.2.7 on 2025-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_studentaccount_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentaccount",
            name="current_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentaccount",
            name="token_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="studentaccount",
            table="accounts_studentaccount",
        ),
    ]
