# Generated by Django 5.2.7 on 2025-11-17 11:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_studentaccount_current_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentaccount",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
