# Generated by Django 5.2.7 on 2025-10-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCatalog",
            fields=[
                (
                    "code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("illustration", models.CharField(default="orange", max_length=32)),
            ],
            options={
                "db_table": "course_catalog",
            },
        ),
        migrations.CreateModel(
            name="CourseTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course_code", models.CharField(max_length=16)),
                ("title", models.CharField(max_length=255)),
                ("deadline", models.DateField()),
                ("brief", models.TextField(blank=True)),
                ("percent_contribution", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "course_task",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=16)),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "material",
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(max_length=64)),
                ("course_code", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "student_enrollment",
                "unique_together": {("student_id", "course_code")},
            },
        ),
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(max_length=64)),
                ("task_id", models.PositiveIntegerField()),
                ("progress", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "task_progress",
                "unique_together": {("student_id", "task_id")},
            },
        ),
    ]
