# Generated by Django 5.2.7 on 2025-10-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course_code", models.CharField(db_index=True, max_length=16)),
                (
                    "qtype",
                    models.CharField(
                        choices=[("mcq", "Multiple Choice"), ("short", "Short Answer")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("text", models.TextField()),
                ("short_answer", models.TextField(blank=True, null=True)),
                ("keywords_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "question",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionKeyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "question_keyword",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, max_length=2, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="courses.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_choice",
                "ordering": ["question_id", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["question", "order"],
                        name="question_ch_questio_0d9a69_idx",
                    )
                ],
                "unique_together": {("question", "order")},
            },
        ),
        migrations.CreateModel(
            name="QuestionKeywordMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.questionkeyword",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_keyword_map",
                "unique_together": {("question", "keyword")},
            },
        ),
    ]
