# Generated by Django 5.2.7 on 2025-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetask",
            name="url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
