# Generated by Django 5.2.7 on 2025-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_question_questionkeyword_questionchoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
