# Generated by Django 4.2.25 on 2025-11-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
