# Generated by Django 4.2.25 on 2025-11-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_taskprogress_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
