# Generated by Django 5.2.7 on 2025-11-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_delete_taskprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursetask",
            name="deadline",
        ),
    ]
