# Generated by Django 5.2.7 on 2025-11-16 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_remove_coursetask_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetask",
            name="deadline",
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 13, 0)),
            preserve_default=False,
        ),
    ]
