# Generated by Django 5.2.7 on 2025-10-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adm_accounts", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAdmin",
            fields=[
                (
                    "code",
                    models.OneToOneField(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="courses.coursecatalog",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        db_column="admin_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_courses",
                        to="adm_accounts.adminaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course-Admin Mapping",
                "verbose_name_plural": "Course-Admin Mappings",
                "db_table": "course_admin",
            },
        ),
    ]
