# Generated by Django 5.2.7 on 2025-10-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentWeeklyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_code", models.CharField(max_length=20)),
                ("week_no", models.PositiveSmallIntegerField()),
                ("daily_hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("weekly_study_days", models.PositiveSmallIntegerField()),
                ("avoid_days_bitmask", models.PositiveSmallIntegerField(default=0)),
                (
                    "mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("default", "Default")],
                        max_length=10,
                    ),
                ),
                (
                    "derived_from_week_no",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.studentaccount",
                    ),
                ),
            ],
            options={
                "db_table": "student_weekly_preferences",
                "unique_together": {("student", "semester_code", "week_no")},
            },
        ),
    ]
