# Generated by Django 5.2.7 on 2025-10-14 06:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_studentaccount_name"),
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPreference",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pref_current",
                        serialize=False,
                        to="accounts.studentaccount",
                    ),
                ),
                (
                    "daily_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.25),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "weekly_study_days",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                ("avoid_days_bitmask", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_preferences",
            },
        ),
        migrations.CreateModel(
            name="StudentPreferenceDefault",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pref_default",
                        serialize=False,
                        to="accounts.studentaccount",
                    ),
                ),
                (
                    "daily_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.25),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "weekly_study_days",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                ("avoid_days_bitmask", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_preferences_default",
            },
        ),
        migrations.DeleteModel(
            name="StudentWeeklyPreference",
        ),
    ]
